Customer refactor list
gabrielkumlehnasaas/asinha pull request #11
Opened 2022-04-18 13:35 UTC by gabrielkumlehnasaas

Adiciona funcionalidade de listagem de customers
![list-customer](https://user-images.githubusercontent.com/101339630/163815890-1b15990f-eac4-4593-b8c8-3448c97dde49.gif)

2022-04-28 02:53 UTC, geanfarias commented on grails-app/services/com/asinha/domain/CustomerService.groovy
> +
se não precisa do código, tira ele do pr, não precisa deixar comentado

2022-04-28 12:24 UTC, gabrielkumlehnasaas commented on grails-app/services/com/asinha/domain/CustomerService.groovy
> +
mas isso já foi deletado, nao achei aqui

2022-05-02 19:19 UTC, geanfarias commented on grails-app/views/customer/list.gsp
> +                        <td>${}</td>
vazio?

2022-05-02 20:13 UTC, gabrielkumlehnasaas commented on grails-app/views/customer/list.gsp
> +                        <td>${}</td>
futuramente vai abrigar o numero de cobranças

2022-05-09 11:48 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
> +    private Integer getCurrentPage() {
Esse tipo de método, vc pode precisar em várias controllers. Vamos supor que exista uma listagem de cobranças em breve, possivelmente será necessário esse tipo de método para buscar o offset. Neste caso, recomendo que seja criado esse método em uma controller separada, algo como BaseController, e que todas as suas controllers tenham o `extends BaseController` assim poderão usar os métodos que existem lá e que são em comum para todas as controllers.

2022-05-09 11:55 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
> +            Integer listPage = Math.round(Math.ceil(customer.id/20))
Por que isso foi necessário?

2022-05-09 11:55 UTC, millenadias commented on grails-app/services/com/asinha/domain/CustomerService.groovy
> +        [customerList: Customer.list(max: 10, offset: getCurrentPage()), totalCount: Customer.count()]
O seu método não está fazendo o return do método criado, faça o return e cria o seu método como `public Map`

2022-05-09 11:55 UTC, millenadias commented on grails-app/services/com/asinha/domain/CustomerService.groovy
> +        [customerList: Customer.list(max: 10, offset: getCurrentPage()), totalCount: Customer.count()]
É possível fazer dessa forma?
```suggestion
        List<Customer> customerList = Customer.list(max: 10, offset: getCurrentPage())
        return [customerList: customerList, totalCount: customerList.totalCount]
```

2022-05-09 17:38 UTC, gabrielkumlehnasaas commented on grails-app/services/com/asinha/domain/CustomerService.groovy
> +        [customerList: Customer.list(max: 10, offset: getCurrentPage()), totalCount: Customer.count()]
o totalCount mantem como Customer.count() né?

2022-05-10 11:23 UTC, millenadias commented on grails-app/views/customer/list.gsp
> +            <table>
Arrumar identação

2022-05-10 11:23 UTC, millenadias commented on grails-app/views/customer/list.gsp
> +
Remover linhas em branco

2022-05-12 13:06 UTC, Yuri-Ferrari requested changes
Façam um merge da branch base desse PR na branch deste PR, estando com a branch 'customerRefactor-list' ativa no seu ambiente de desenvolvimento, rode o comando, `git merge customerRefactor`.
Pois este PR está mostrando muitas alterações que já foram incluídas na PR predecessora.

2022-05-16 13:19 UTC, Yuri-Ferrari approved these changes

2022-05-16 13:19 UTC, Yuri-Ferrari commented on src/main/groovy/com/asinha/base/BaseController.groovy
> +        if(!params.offset) params.offset = 0
```suggestion
        if (!params.offset) params.offset = 0

```
Ajuda na leitura do código

2022-05-16 16:48 UTC, merged