Customer refactor edit
gabrielkumlehnasaas/asinha pull request #14
Opened 2022-04-22 14:56 UTC by gabrielkumlehnasaas

Adiciona funcionalidades de edição com update de informações
- view edit
- js para povoar inputs com dados de customer
- controller e service para salvar alterações 
- adiciona botões de edição em list e show
![edit-customer](https://user-images.githubusercontent.com/101339630/164740241-732bb268-ed80-4b6d-9a42-553a9855bbc6.gif)

2022-05-02 19:20 UTC, geanfarias commented on grails-app/views/customer/list.gsp
> +                        <th scope="col">#ID</th>
precisa do scope?

2022-05-02 19:21 UTC, geanfarias commented on grails-app/views/customer/list.gsp
> +                            <td>${}</td>
vazio?

2022-05-09 12:06 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
> +        Integer id = params.int("id")
Como o id é usado direto na consulta, não precisar criar uma var pra isso. Outro ponto, no caso do projeto não teremos cenários assim, mas no asaas sempre usamos long para o id, considerando que a tabela pode ficar cheia de registros e sendo assim, se torna um long, legal vcs já irem usando também. Quando vamos buscar por id, podemos usar o get na própria domain passando o id direto, ve se funciona nesse caso.
```suggestion
        return [customer: Customer.get(params.long("id"))]        
```

2022-05-09 12:06 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
> +        def update() {
Arrumar identação

2022-05-09 12:06 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
> +                if (customer){
Aplicar em demais cenários nessa controller.
```suggestion
                if (customer) redirect([action: "show", id: customer.id])
```

2022-05-09 12:06 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
> +            } catch(Exception exception) {}
O catch não está retornando nada, inclua algo no catch ou remove ele.

2022-05-09 12:06 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
>          } catch(Exception exception) {
Não tem nada no catch, sendo assim ele pode ser removido, ou inclua algo nele.

2022-05-09 12:06 UTC, millenadias commented on grails-app/views/customer/list.gsp
> +        <%-- <meta name="layout" content="main"/> --%>
Pode ser removido?

2022-05-09 12:13 UTC, millenadias commented on grails-app/domain/com/asinha/domain/Customer.groovy
> +    Boolean deleted = false
Por que foram incluídas essas colunas direto na domain ao invés de usar o BaseEntity?

2022-05-09 18:09 UTC, gabrielkumlehnasaas commented on grails-app/views/customer/list.gsp
> +        <%-- <meta name="layout" content="main"/> --%>
tem mais pra frente uma branch que cria uma main de fato, estamos esperando o merge dela pra poder usar direto o layout main

2022-05-16 13:26 UTC, Yuri-Ferrari requested changes

2022-05-16 13:26 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/customer-show.js
> +            console.log(response);
Logs de teste não devem ir para os PRs.

2022-05-16 13:26 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/customer-show.js
> +    this.init = function() {
Pra facilitar a leitura, coloquem esse método no começo do js, afinal ele é o primeiro a ser chamado.

2022-05-16 13:26 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/customer-show.js
> +function CustomerShow() {
Como é possível alterar e não somente mostrar as informações, vale encontrar um nome que englobe tudo o que este Controller faz, além disso, vale incluir o sufixo 'Controller'

2022-05-17 11:39 UTC, Yuri-Ferrari approved these changes

2022-05-17 11:39 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/customer-show.js
> +function CustomerShowAndEditController() {
Alterar nome do arquivo para refletir o nome do controller

2022-05-17 12:29 UTC, merged