refatora list, com funcionalidade de criterio
gabrielkumlehnasaas/asinha pull request #20
Opened 2022-05-02 17:54 UTC by gabrielkumlehnasaas

Adiciona funcionalidade de listagem de payers, filtrado para cada customer

![payer-list](https://user-images.githubusercontent.com/101339630/166299323-7f9453fa-8129-457a-a7db-b8d8d1d87597.gif)

pr anterior #19

2022-05-09 12:21 UTC, millenadias commented on grails-app/views/payer/list.gsp
> +            <table>
Arrumar identação

2022-05-16 13:51 UTC, Yuri-Ferrari requested changes

2022-05-16 13:51 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payer-create.js
> +            if (response.success) {
Utilizar earlyReturn e sempre tratamos o erro, o sucesso deve seguir o caminho normal do método
```suggestion
            if (!response.success) {
             Tratativa do Erro
             return
            }
            Tratativa do Sucesso
```

2022-05-16 13:51 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PayerController.groovy
> +
Remover linhas vazias desnecessárias

2022-05-16 13:51 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +        def payerList = payerCriteria.list(max: max, offset: offset) {
Unificar essas duas linhas e tipar a variável.

2022-05-16 13:51 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +    public List<Payer> getPayersByCustomer(customerId, max, offset) {
Tipar parâmetros

2022-05-16 13:51 UTC, Yuri-Ferrari commented on grails-app/views/payer/list.gsp
> +        <%-- <meta name="layout" content="main"/> --%>
Códigos comentados não devem ir para PR

2022-05-17 11:51 UTC, Yuri-Ferrari requested changes

2022-05-17 11:51 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +    public List<Payer> getPayersByCustomer(customerId, max, offset) {
Tipar parâmetros

2022-05-17 17:25 UTC, Yuri-Ferrari requested changes

2022-05-17 17:25 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +        return payerList
Esse trecho de código funciona?

2022-05-17 18:21 UTC, gabrielkumlehnasaas commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +        return payerList
corrigido

2022-05-17 18:31 UTC, closed without merging