Payer refactor show/edit
gabrielkumlehnasaas/asinha pull request #21
Opened 2022-05-02 18:00 UTC by gabrielkumlehnasaas

Adiciona funcionalidade de show e edit no payer
![image](https://user-images.githubusercontent.com/101339630/166300097-a4c6fdf3-f0a3-4403-987c-7206d61425d4.png)

pr anterior #20

2022-05-09 12:20 UTC, millenadias commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +    def getPayer(Integer id) {
Se for feito o get direto no controller, pode ser removido.

2022-05-09 12:20 UTC, millenadias commented on grails-app/services/com/asinha/domain/PayerService.groovy
>      def save(Map params) {
```suggestion
    public Payer save(Map params) {
```

2022-05-10 18:12 UTC, gabrielkumlehnasaas commented on grails-app/views/payer/create.gsp
> +
o p id error ?

2022-05-16 13:56 UTC, Yuri-Ferrari requested changes

2022-05-16 13:56 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payer-show.js
> +    this.init = function() {
Reordenar

2022-05-16 13:56 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payer-show.js
> +            console.log(response);
Remover logs de teste

2022-05-16 13:56 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payer-show.js
> +function PayerShow() {
Renomear, esse controller faz mais do que apenas mostrar as informações

2022-05-16 13:56 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PayerController.groovy
> +    def show(){
```suggestion
    def show() {
```

2022-05-16 13:56 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PayerController.groovy
> +            if (payer) redirect([action: "show", payerId: payer.id])
Esse redirect funciona?

2022-05-16 13:56 UTC, Yuri-Ferrari commented on grails-app/views/payer/show.gsp
> +        <asset:javascript src="application.js"/>
Pode ser usado o layout 'main' aqui?

2022-05-16 17:46 UTC, gabrielkumlehnasaas commented on grails-app/controllers/com/asinha/domain/PayerController.groovy
> +            if (payer) redirect([action: "show", payerId: payer.id])
agora sim kkkk

2022-05-17 12:53 UTC, Yuri-Ferrari requested changes

2022-05-17 12:53 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PayerController.groovy
> +            if(payer) render ([success: true] as JSON)
```suggestion
            if (payer) render ([success: true] as JSON)
```

2022-05-17 12:53 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/CustomerService.groovy
> +        println(params)
Remover

2022-05-17 17:27 UTC, Yuri-Ferrari approved these changes

2022-05-17 18:24 UTC, merged