Payment domain
gabrielkumlehnasaas/asinha pull request #22
Opened 2022-05-10 17:00 UTC by gabrielkumlehnasaas

Adiciona o Domínio de Payment com respectivos Enums e Utils necessárias

pr anterior #21

2022-05-16 14:06 UTC, Yuri-Ferrari requested changes

2022-05-16 14:06 UTC, Yuri-Ferrari commented on grails-app/domain/com/asinha/domain/Payment.groovy
> +    Customer customer
Faltou os imports

2022-05-16 14:06 UTC, Yuri-Ferrari commented on src/main/groovy/com/asinha/enums/PaymentMethod.groovy
> +    CARD,
Vale separar os tipos de operações de cartão?

2022-05-16 14:06 UTC, Yuri-Ferrari commented on src/main/groovy/com/asinha/utils/CustomDateUtils.groovy
> +package com.asinha.utils
É usado neste PR?
É uma boa prática incluir somente códigos que serão usados no escopo do PR, isso além de facilitar o histórico, ajuda o revisor, afinal eu não sei como esse método será usado e por conta disso não sei se é a melhor implementação possível.

2022-05-16 17:54 UTC, gabrielkumlehnasaas commented on src/main/groovy/com/asinha/enums/PaymentMethod.groovy
> +    CARD,
os métodos de pagamentos foram passados pelo marlon e lucas, acho que não é necessário distinguir entre debito e credito no nosso projeto

2022-05-16 17:57 UTC, gabrielkumlehnasaas commented on src/main/groovy/com/asinha/utils/CustomDateUtils.groovy
> +package com.asinha.utils
realmente ele só é usado na próxima branch. apagado

2022-05-17 12:53 UTC, Yuri-Ferrari requested changes

2022-05-17 12:53 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payer-show.js
> +<<<<<<< HEAD
Creio que rolou um problema de merge aqui

2022-05-17 18:24 UTC, merged