reaorganiza imports de create
gabrielkumlehnasaas/asinha pull request #23
Opened 2022-05-10 18:18 UTC by gabrielkumlehnasaas

Cria a view de criação de uma cobrança com valor, descrição, método de pagamento, data de vencimento e um pagador selecionado de uma listagem

![create-payment](https://user-images.githubusercontent.com/101339630/167695713-b5e3416d-5d30-4953-b34b-bebcfc4398b7.gif)

pr anterior #22

2022-05-12 11:33 UTC, millenadias commented on grails-app/controllers/com/asinha/domain/PayerController.groovy
> +        List<Payer> payerList = payerService.getPayersByCustomer(params.long("id"), getLimitPerPage(), getCurrentPage())
Esse `params.id` é o `customerId` certo? Não seria coerente renomeá-lo para que o nome fique coerente com o valor que ele realmente carrega? No caso, o `customerId`

2022-05-12 11:33 UTC, millenadias commented on grails-app/views/customer/show.gsp
>                  </div>
Tem essa div depois do `</html>`, revisem a estrutura desse gsp

2022-05-12 12:34 UTC, Hebeert commented on grails-app/controllers/com/asinha/domain/PayerController.groovy
> +        List<Payer> payerList = payerService.getPayersByCustomer(params.long("id"), getLimitPerPage(), getCurrentPage())
Sim, ajustado

2022-05-12 12:39 UTC, Hebeert commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +    public List<Payer> getPayersByCustomer(customerId, max = null, offset = null) {
Ajustado

2022-05-12 13:45 UTC, Hebeert commented on grails-app/views/payment/create.gsp
> +            <form class="form row" id="create-form" data-redirect="${ g.createLink([controller:'payment', action:'list', params:[id: customerId]])}" action="${ g.createLink([controller:'payment', act
Ajustado

2022-05-12 14:25 UTC, Hebeert commented on grails-app/controllers/com/asinha/domain/PaymentController.groovy
> +            if(payment) render([success: true] as JSON)
Adicionado no catch : render([success: false, message: "Erro, tente novamente. Erro: "+ exception.message] as JSON

2022-05-12 14:45 UTC, Hebeert commented on grails-app/controllers/com/asinha/domain/CustomerController.groovy
> +            render([success: false, message: "Erro, tente novamente. Erro: "+ exception.message] as JSON)
Estamos utilizando as tratativas de erro via json JS com máscaras, assim aparecerá a mensagem de erro para o usuário menos técnico

2022-05-16 14:15 UTC, Yuri-Ferrari requested changes

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payment-create.js
> +        $("#value").maskMoney({prefix:'R$ ', allowNegative: false, thousands:',', decimal:'.', affixesStay: false});
Vale componetizar máscaras que poderão ser usadas em outros lugares da aplicação

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payment-create.js
> +                console.log("erro")
Remover logs de testes

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payment-create.js
> +    this.init = function() {
Reordenar

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PaymentController.groovy
> +import static org.springframework.http.HttpStatus.*
Vale importar apenas o que é usado, dessa forma está sendo importado diversas classe que podem nem ser usadas.

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PaymentController.groovy
> +        try {Payment payment = paymentService.save(params)
Pular linha

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PaymentController.groovy
> +            if(payment) render([success: true] as JSON)
```suggestion
            if (payment) render([success: true] as JSON)
```

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/controllers/com/asinha/domain/PaymentController.groovy
> +        } catch(Exception exception) {
```suggestion
        } catch (Exception exception) {
```

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +    public List<Payer> getPayersByCustomer(customerId, max = null, offset = null) {
Tipar parâmetros

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +        } else {
Podes remover esse else, afinal se a execução 'caiu' no IF ele sairá do código

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +            def payerList = payerCriteria.list() {
Tipar variável

2022-05-16 14:15 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +            def payerList = payerCriteria.list(max: max, offset: offset) {
Tipar

2022-05-17 12:56 UTC, Yuri-Ferrari requested changes

2022-05-17 12:56 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payer-show.js
> +    };e
Sobrou algo aqui

2022-05-17 12:56 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/asinha/payment-create.js
> +function PaymentCreate() {
Utilizar sufixo controller e mudar o nome do arquivo também

2022-05-17 12:56 UTC, Yuri-Ferrari commented on grails-app/services/com/asinha/domain/PayerService.groovy
> +    public List<Payer> getPayersByCustomer(customerId, Integer max = null, Integer offset = null) {
Tipar parâmetros

2022-05-17 12:56 UTC, Yuri-Ferrari commented on src/main/groovy/com/asinha/utils/CustomDateUtils.groovy
> +package com.asinha.utils
Ficou top, parabéns jovens!

2022-05-17 17:28 UTC, Yuri-Ferrari approved these changes

2022-05-17 18:28 UTC, merged